apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lesson3mariadb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Password must be encoded in Base64:
  #   echo -n "root" | base64
  # The result of the operation:
  #   root -> cm9vdA==
  ROOT_PASSWORD: {{ printf .Values.lesson3mariadb.auth.password | b64enc }}
